### ISSUE TITLE
formating problem with some browsers

### ISSUE THREAD

**Issue by pavel-demin** [sefffal/redpitaya-multichannelanalyser#3]
Hi Will,

I've just tested this web application with a random set of browsers:
 - Firefox 51
 - Firefox 59
 - Internet Explorer 11
 - Safari iOS 11

Only Firefox 59 shows the interface correctly.

Firefox 51 and Internet Explorer 11 show it like on this screenshot:
![redpitaya-multichannelanalyser-ie-11](https://user-images.githubusercontent.com/8037893/37877673-158a12cc-304e-11e8-8837-233ad7eb25bb.png)

Safari iOS 11 worked slightly better but still with some formatting problems.

Any idea on how to fix this?

Best regards,

Pavel

**Comment by sefffal** [comment]
Hi Pavel,
Thanks very much for testing it out!
To do the layout, I used a fairly new standard called CSS Grids since it makes it easy to have different layouts for different screen sizes.

There is a browser compatibility chart [here](https://caniuse.com/#feat=css-grid). If you click "usage relative" it shows about 85% support, which I am mostly satisfied with.
One straightforward thing we can do is add support for MS IE 11 by adding a few new rules to the CSS.

Would you mind sending a screenshot of it running on iOS 11?

**Comment by pavel-demin** [comment]
Thanks for the explanation and for the link to the compatibility chart.

Here are two iOS screenshots:
![redpitaya-multichannelanalyser-ios-1](https://user-images.githubusercontent.com/8037893/38127509-f3d39e0a-33e5-11e8-8038-51b85014db24.png)
![redpitaya-multichannelanalyser-ios-2](https://user-images.githubusercontent.com/8037893/38127510-f3ef0532-33e5-11e8-8a7f-4231aa8c3f3a.png)

As you can see, the formatting is slightly off and the time is almost unreadable when the data acquisition is running.

**Comment by pavel-demin** [comment]
Just noticed that there is a typo in SETTINGS.

**Comment by sefffal** [comment]
Okay,
I improved support for older browsers, especially IE 11 in this commit d16835f95de10ad9a77f310bcf004d79e385d007.

Thanks for spotting the typo in settings! Hard to beleive I missed that. It's fixed now.

**Comment by pavel-demin** [comment]
The latest version works very well with IE 11. Thanks for this update.
